version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: bootsnap
    versions:
    - 1.7.1
    - 1.7.2
    - 1.7.3
  - dependency-name: appsignal
    versions:
    - 2.11.6
    - 2.11.8
    - 2.11.9
    - 3.0.0
    - 3.0.1
    - 3.0.2
  - dependency-name: omniauth
    versions:
    - 2.0.3
  - dependency-name: rails
    versions:
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
  - dependency-name: faker
    versions:
    - 2.16.0
  - dependency-name: puma
    versions:
    - 5.2.1
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@prettier/plugin-ruby"
    versions:
    - 1.5.2
    - 1.5.3
    - 1.5.4
  - dependency-name: stylelint
    versions:
    - 13.10.0
    - 13.11.0
    - 13.12.0
  - dependency-name: "@rails/activestorage"
    versions:
    - 6.1.2
  - dependency-name: "@rails/ujs"
    versions:
    - 6.1.2
  - dependency-name: "@rails/actioncable"
    versions:
    - 6.1.2
