---

inherit_from:
  - https://raw.githubusercontent.com/thoughtbot/guides/4240c34185e8a9a31f5f735808516b52caa5c05e/style/ruby/.rubocop.yml
require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-minitest
  - rubocop-performance
Metrics/LineLength:
  Exclude:
    - config/routes.rb
AllCops:
  Exclude:
    - bin/*
    - db/**/*
    - node_modules/*
    - Guardfile
Layout/DotPosition:
  EnforcedStyle: leading
