development: &default
  adapter: postgresql
  database: resourcer_development
  encoding: utf8
  min_messages: warning
  pool: <%= Integer(ENV.fetch("DB_POOL", 5)) %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  timeout: 5000
  host: <%= ENV.fetch("DB_HOST", "localhost") %>

test:
  <<: *default
  database: resourcer_test

production: &deploy
  adapter: postgresql
  encoding: utf8
  min_messages: warning
  pool: <%= [Integer(ENV.fetch("MAX_THREADS", 5)), Integer(ENV.fetch("DB_POOL", 5))].max %>
  timeout: 5000
  database: resourcer_production
  username: resourcer_production
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_SOCKET"] %>
