name: Lint

on: [push, pull_request]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Rubocop checks
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: gimenete/rubocop-action@1.0
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: ESLint
      uses: stefanoeb/eslint-action@1.0.2
      with:
        files: app/javascript
        repo-token: ${{ secrets.GITHUB_TOKEN }}
